resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'saravananmohan2410/saravananmohan2410dockerimage:$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Firstbuildandpush'
        command: 'Build an image'
        dockerFile: '$(Build.SourcesDirectory)/Dockerfile'
        imageName: '$(ImageName)'
        useDefaultContext: false
    

    - task: Docker@1
      inputs:
         containerregistrytype: 'Container Registry'
         dockerRegistryEndpoint: 'Firstbuildandpush'
         command: 'Push an image'
         imageName: '$(ImageName)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
      displayName: 'Push the Docker image to Dockerhub' 