resources:
- repo: self

pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'saravananmohan2410dockerimage/saravanan:$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Firstbuildandpush'
        command: 'Build an image'
        dockerFile: '$(Build.SourcesDirectory)/Dockerfile'
        imageName: '$(ImageName)'
        useDefaultContext: false